disabled_rules:
  - missing_docs
  - function_body_length
  - type_body_length
opt_in_rules:
  - empty_count
  - colon
  - comma
  - control_statement
included:
  - ASToast/Source
excluded:
  - Carthage
  - Pods
force_cast: warning
force_try:
  severity: warning
line_length: 210
file_length:
  warning: 700
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
function_parameter_count: 8
large_tuple:
  warning: 5
  error: 6
variable_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode"