language: objective-c
xcode_workspace: ASToast.xcworkspace
osx_image: xcode8
xcode_scheme: ASToast
xcode_sdk: iphonesimulator10.0

branches:
 only: master

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/ASToast-*/
- rvm use $RVM_RUBY_VERSION
- brew update; brew outdated swiftlint || brew upgrade swiftlint

install:
- bundle
- bundle install --without=documentation --path ../travis_bundle_dir

script:
- xcodebuild -workspace ASToast.xcworkspace -scheme ASToast -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0" clean test | xcpretty

after_success: slather